#debug: true
spring:
  datasource:
    username: root
    password: haojunjie
    url: jdbc:mysql://10.128.0.6:9999/blog
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 10.128.0.6
    port: 8890
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  messages:
    basename: i18n.register
  #引入国际化资源文件
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

