#debug: true
spring:
  datasource:
    username: root
    password: haojunjie
    url: jdbc:mysql://192.168.10.200:9999/blog
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.10.200
    port: 8890
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


